//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoASPMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Alumno
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50,
                      ErrorMessage = "{0} debe tener al menos {2} caracteres de longitud",
                      MinimumLength = 3)]
        [Display(Name = "Nombre Completo")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50,
                      ErrorMessage = "{0} debe tener al menos {2} caracteres de longitud",
                      MinimumLength = 3)]
        [Display(Name = "Apellido Completo")]
        public string Apellido { get; set; }
        [Required]
        [Phone]
        public string Telefono { get; set; }
        [Required]
        [Display(Name = "Promedio de Notas")]
        [Range(1, 100, ErrorMessage = "Por favor ingresa un promedio válido")]
        public int PromedioNota { get; set; }
    }
}
